version: '3.8'

services:
  # PHP Backend
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: iftixor_backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=mysql
      - DB_NAME=portfolio_db
      - DB_USER=root
      - DB_PASS=rootpassword
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - portfolio_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: iftixor_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - portfolio_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: iftixor_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - portfolio_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: iftixor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio_network

  # Nginx (Production)
  nginx:
    image: nginx:alpine
    container_name: iftixor_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - portfolio_network
    profiles:
      - production

volumes:
  mysql_data:
  redis_data:

networks:
  portfolio_network:
    driver: bridge